
const imageSeeder = () => {
  const photoArr = [
    'https://i.imgur.com/dFt5Vp7.jpg',
    'https://i.imgur.com/GIjDs2Z.jpg',
    'https://i.imgur.com/lbo0tID.jpg',
    'https://i.imgur.com/pWMrSOX.jpg',
    'https://i.imgur.com/7rHZXHm.jpg',
    'https://i.imgur.com/WSzV4Y5.jpg',
    'https://i.imgur.com/locZ7ga.jpg',
    'https://i.imgur.com/39lNeqn.jpg',
    'https://i.imgur.com/PS4XYPC.jpg',
    'https://i.imgur.com/9Fvj0Ma.jpg',
    'https://i.imgur.com/F5LllA4.jpg',
    'https://i.imgur.com/I4Lq0tj.jpg',
    'https://i.imgur.com/dVAlPBd.jpg',
    'https://i.imgur.com/tOk0XfQ.jpg',
    'https://i.imgur.com/KpNSHUS.jpg',
    'https://i.imgur.com/vE0vnFx.jpg',
    'https://i.imgur.com/VlfCDv7.jpg',
    'https://i.imgur.com/FYrQsgc.jpg',
    'https://i.imgur.com/Nd1gSBr.jpg',
    'https://i.imgur.com/KWSsxVb.jpg',
    'https://i.imgur.com/4oLlklt.jpg',
    'https://i.imgur.com/B3HHnX0.jpg',
    'https://i.imgur.com/pAg6DUz.jpg',
    'https://i.imgur.com/vjoeY2K.jpg',
    'https://i.imgur.com/jYD44XW.jpg',
    'https://i.imgur.com/XoMYNGK.jpg',
    'https://i.imgur.com/Tc8u4OY.jpg',
    'https://i.imgur.com/vSwK0MH.jpg',
    'https://i.imgur.com/GCMuQg9.jpg',
    'https://i.imgur.com/2sEyFGt.jpg',
    'https://i.imgur.com/XKUdviS.jpg',
    'https://i.imgur.com/jee0w0i.jpg',
    'https://i.imgur.com/l7KuE4X.jpg',
    'https://i.imgur.com/2NkPcHB.jpg',
    'https://i.imgur.com/PXUcYyb.jpg',
    'https://i.imgur.com/vYoc47i.jpg',
    'https://i.imgur.com/Ld8cGdi.jpg',
    'https://i.imgur.com/VOsWoC3.jpg',
    'https://i.imgur.com/QLAh53v.jpg',
    'https://i.imgur.com/BEUllsg.jpg',
    'https://i.imgur.com/HbpXdx1.jpg',
    'https://i.imgur.com/HbpXdx1.jpg',
    'https://i.imgur.com/u9ftxCh.jpg',
  ];
  const count = photoArr.length;
  return photoArr[Math.floor(Math.random() * count)];
};

module.exports = imageSeeder;
