const faker = require('faker');
const similarMoviesSeeder = require('../randomData/similarMoviesSeeder.js');
const descriptionGen = require('../randomData/descriptionGenerator.js');
const randomYear = require('../randomData/randomYear.js');
const ratingGen = require('../randomData/ratingGenerator.js');
const starsSeeder = require('../randomData/starsSeeder.js');

const movieData = [{
  movieName: 'Rubber',
  movieID: 1,
  year: 2010,
  image: 'https://i.imgur.com/2sEyFGt.jpg',
  rating: 'R',
  reviewScore: 5.8,
  description: 'A homicidal car tire, discovering it has destructive psionic power, sets its sights on a desert town once a mysterious woman becomes its obsession.',
  director: 'Quentin Dupieux',
  stars: ['Stephen Spinella', 'Roxane Mesquida', 'Wings Hauser'],
  similarMovies: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  genre: 'Horror',
},
{
  movieName: 'McLintock!',
  movieID: 7,
  year: 1963,
  image: 'https://i.imgur.com/vSwK0MH.jpg',
  rating: 'Passed',
  reviewScore: 7.2,
  description: 'Wealthy rancher G.W. McLintock uses his power and influence in the territory to keep the peace between farmers, ranchers, land-grabbers, Indians and corrupt government officials.',
  director: 'Anderw V. McLeaglen',
  stars: ['John Wayne', 'Maureen O\'Hara', 'Patrick Wayne'],
  similarMovies: similarMoviesSeeder(),
  genre: 'Westerm',
},
{
  movieName: 'Zoolander',
  movieID: 9,
  year: 2001,
  image: 'https://i.imgur.com/Tc8u4OY.jpg',
  rating: 'PG-13',
  reviewScore: 6.5,
  description: 'At the end of his career, a clueless fashion model is brainwashed to kill the Prime Minister of Malaysia.',
  director: 'Ben Stiller',
  stars: ['Ben Stiller', 'Owen Wilson', 'Christine Taylor'],
  similarMovies: similarMoviesSeeder(),
  genre: 'Comedy',
},
{
  movieName: 'Wedding Crashers',
  movieID: 11,
  year: 2005,
  image: 'https://i.imgur.com/GCMuQg9.jpg',
  rating: 'R',
  reviewScore: 6.9,
  description: 'John Beckwith and Jeremy Grey, a pair of committed womanizers who sneak into weddings to take advantage of the romantic tinge in the air, find themselves at odds with one another when John meets and falls for Claire Cleary.',
  director: 'David Dobkin',
  stars: ['Owen Wilson', 'Vince Vaughn', 'Rachel McAdams'],
  similarMovies: similarMoviesSeeder(),
  genre: 'Comedy',
},
{
  movieName: 'Face/Off',
  movieID: 5,
  year: 1997,
  image: 'https://i.imgur.com/XoMYNGK.jpg',
  rating: 'R',
  reviewScore: 7.3,
  description: 'In order to foil a terrorist plot, an FBI agent undergoes facial transplant surgery and assumes the identity of a criminal mastermind, who murdered his only son. The plan turns sour when the criminal wakes up prematurely and seeks revenge.',
  director: 'John Woo',
  stars: ['John Travoltoa', 'Nicolas Cage', 'Joan Allen'],
  similarMovies: similarMoviesSeeder(),
  genre: 'Sci-Fi',
},
{
  movieName: faker.fake('{{name.title}}'),
  movieID: 6,
  year: randomYear(),
  image: 'https://i.imgur.com/HbpXdx1.jpg',
  rating: ratingGen(),
  reviewScore: Math.floor(Math.random() * 11),
  description: descriptionGen(),
  director: faker.fake('{{name.firstName}} {{name.lastName}}'),
  stars: starsSeeder(),
  similarMovies: similarMoviesSeeder(),
  genre: faker.fake('{{lorem.word}}'),
},
{
  movieName: faker.fake('{{name.title}}'),
  movieID: 2,
  year: randomYear(),
  image: 'https://i.imgur.com/2NkPcHB.jpg',
  rating: ratingGen(),
  reviewScore: Math.floor(Math.random() * 11),
  description: descriptionGen(),
  director: faker.fake('{{name.firstName}} {{name.lastName}}'),
  stars: starsSeeder(),
  similarMovies: similarMoviesSeeder(),
  genre: faker.fake('{{lorem.word}}'),
},
{
  movieName: faker.fake('{{name.title}}'),
  movieID: 8,
  year: randomYear(),
  image: 'https://i.imgur.com/jee0w0i.jpg',
  rating: ratingGen(),
  reviewScore: Math.floor(Math.random() * 11),
  description: descriptionGen(),
  director: faker.fake('{{name.firstName}} {{name.lastName}}'),
  stars: starsSeeder(),
  similarMovies: similarMoviesSeeder(),
  genre: faker.fake('{{lorem.word}}'),
},
{
  movieName: faker.fake('{{name.title}}'),
  movieID: 3,
  year: randomYear(),
  image: 'https://i.imgur.com/BEUllsg.jpg',
  rating: ratingGen(),
  reviewScore: Math.floor(Math.random() * 11),
  description: descriptionGen(),
  director: faker.fake('{{name.firstName}} {{name.lastName}}'),
  stars: starsSeeder(),
  similarMovies: similarMoviesSeeder(),
  genre: faker.fake('{{lorem.word}}'),
},
{
  movieName: faker.fake('{{name.title}}'),
  movieID: 10,
  year: randomYear(),
  image: 'https://i.imgur.com/QLAh53v.jpg',
  rating: ratingGen(),
  reviewScore: Math.floor(Math.random() * 11),
  description: descriptionGen(),
  director: faker.fake('{{name.firstName}} {{name.lastName}}'),
  stars: starsSeeder(),
  similarMovies: similarMoviesSeeder(),
  genre: faker.fake('{{lorem.word}}'),
},
{
  movieName: faker.fake('{{name.title}}'),
  movieID: 4,
  year: randomYear(),
  image: 'https://i.imgur.com/7rHZXHm.jpg',
  rating: ratingGen(),
  reviewScore: Math.floor(Math.random() * 11),
  description: descriptionGen(),
  director: faker.fake('{{name.firstName}} {{name.lastName}}'),
  stars: starsSeeder(),
  similarMovies: similarMoviesSeeder(),
  genre: faker.fake('{{lorem.word}}'),
},
];

module.exports = movieData;
